name: Build resume.pdf and deploy to gh-pages

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: update packages
      run: sudo apt-get update
    - name: install pandoc and latex
      run: sudo apt-get install pandoc texlive-latex-extra -y
    - name: make resume 
      run: pandoc resume.yaml -o resume.pdf --pdf-engine=pdflatex --template=resume-template.tex
    - name: get last commit hash code
      run: echo "LAST_COMMIT=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
    - name: commit resume
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m "Update resume.pdf for commit ${{ env.LAST_COMMIT }}"
        git push
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get original resume updating commit hash
        run: echo "LAST_COMMIT=$(git rev-parse --short HEAD^)" >> $GITHUB_ENV
      - name: Copy resume.pdf to gh-pages
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout gh-pages
          git checkout master resume.pdf
          git commit -m "Update resume.pdf for commit ${{ env.LAST_COMMIT }}"
          git push