# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it  
    - uses: actions/checkout@v2
    - uses: docker://pandoc/latex
      with:
        args: resume.yaml -o resume.pdf --pdf-engine=pdflatex --template=resume-template.tex

    - name: make & commit resume
      run: |
        git config user.name emcauliffe
        git config user.email 14607273+emcauliffe@users.noreply.github.com
        git add .
        git commit -m "Update resume.pdf for commit $LAST_COMMIT"
        git push
      env:
        LAST_COMMIT: git ls-remote https://github.com/emcauliffe/resume.git HEAD | cut -c1-7
