name: Build resume.pdf

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: update packages
      run: sudo apt-get update
    - name: install pandoc and latex
      run: sudo apt-get install pandoc texlive-latex-extra -y
    - name: make resume 
      run: pandoc resume.yaml -o resume.pdf --pdf-engine=pdflatex --template=resume-template.tex
    - name: get last commit hash code
      run: echo "LAST_COMMIT=$(git ls-remote https://github.com/emcauliffe/resume.git HEAD | cut -c1-7)" >> $GITHUB_ENV
    - name: commit resume
      run: |
        git config user.name emcauliffe
        git config user.email 14607273+emcauliffe@users.noreply.github.com
        git add .
        git commit -m "Update resume.pdf for commit ${{ env.LAST_COMMIT }}"
        git push
